---
name: Checks

on: [push]  # Trigger

jobs:
  test-lint:  # job ID
    name: Test and Lint
    runs-on: ubuntu-20.04   # with preinstalled docker-compose
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unit Tests
        run: docker-compose run --rm app1 sh -c "python manage.py test"
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"
